# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [ ]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    
    Parameters:
    - mode (str): Type of array to create ('zeros', 'ones', 'full', 'identity').
    - shape (int or tuple): Shape of the array. For 'identity', must be an int (size of square matrix).
    - value: Value to fill the array with when mode is 'full'.
    
    Returns:
    - np.ndarray: The created NumPy array.
    """
    
    if mode == 'zeros':
        return np.zeros(shape)
    
    elif mode == 'ones':
        return np.ones(shape)
    
    elif mode == 'full':
        if value is None:
            raise ValueError("You must provide a 'value' for full mode.")
        return np.full(shape, value)
    
    elif mode == 'identity':
        if not isinstance(shape, int):
            raise ValueError("Shape must be an integer for identity mode.")
        return np.identity(shape)
    
    else:
        raise ValueError(f"Unknown mode '{mode}'. Valid modes are: 'zeros', 'ones', 'full', 'identity'.")


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [ ]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.

    Parameters:
    - data1: First dataset (list, tuple, or ndarray)
    - data2: Second dataset (list, tuple, or ndarray)
    - new_shape: Shape to reshape data1 into (tuple, e.g., (rows, cols))

    Returns:
    - combined_dataset: Vertically stacked NumPy array
    """
    try:
        # Step 1: Convert inputs to ndarray
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Step 2: Reshape arr1 to the requested shape
        reshaped_arr1 = arr1.reshape(new_shape)

        # Step 3: Check if column counts match for vertical stacking
        if reshaped_arr1.shape[1] != arr2.shape[1]:
            raise ValueError(f"Column mismatch: reshaped_arr1 has {reshaped_arr1.shape[1]} columns, "
                             f"but arr2 has {arr2.shape[1]} columns.")

        # Step 4: Vertical stacking
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Handle reshape errors or column mismatches
        raise ValueError(f"Company-grade Error: {e}")


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [ ]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.

    Parameters:
    - arr: Input array (list, tuple, or ndarray)
    - threshold: Numeric threshold value
    - replacement_value: Value to replace elements that meet the condition (default -1)

    Returns:
    - modified_arr: NumPy array with replacements applied
    """
    # Step 1: Convert input to a NumPy array
    arr = np.array(arr)

    # Step 2: Define the condition (elements >= threshold)
    condition = arr >= threshold

    # Step 3: Apply modification using np.where
    modified_arr = np.where(condition, replacement_value, arr)

    return modified_arr


TestCase

In [ ]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = apply_threshold(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


: 

In [ ]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])